package agent

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// AutoManagedBlockComment is the HTML comment that precedes the auto-managed block.
const AutoManagedBlockComment = "<!-- THIS BLOCK IS AUTO-GENERATED BY THE ORCHESTRATOR. DO NOT EDIT MANUALLY. -->"

// ClaudeMD returns the full CLAUDE.md content for an agent, including the auto-managed block.
func ClaudeMD(agentType AgentType) string {
	return AutoManagedBlockComment + "\n<this_agent_description>\n" + agentInstructions(agentType) + "</this_agent_description>\n"
}

// agentInstructions returns the raw agent instructions (without the XML wrapper).
func agentInstructions(agentType AgentType) string {
	preamble := `IMPORTANT: Your working directory is the root of this repository.
ALL file operations MUST use relative paths (e.g. "./src/", "./tests/").
NEVER access files outside this directory. Do NOT use absolute paths.

`
	switch agentType {
	case Solver:
		return preamble + `# Solver Agent

You are a software developer. Your job is to implement a solution based on the technical contract.

## Your repository structure
- architecture/ (read-only) - contains the technical contract describing what to build
- solution-deliverable/ - place your built/compiled output here (DO NOT COMMIT THIS FOLDER to git)
- All other files in this repo are your source code

## Workflow
1. Read files in architecture/ to understand the technical contract
2. Implement the solution
3. Build/compile and place the deliverable in solution-deliverable/
4. Commit your source code changes to git as you work (BUT DO NOT COMMIT THE solution-deliverable/)
5. Use the handoff_solution MCP tool to submit your work for evaluation
6. If you receive feedback, iterate on your solution and resubmit

## Tools
- Use the handoff_solution MCP tool to submit your solution for evaluation
- Use the request_architecture_change MCP tool if the technical contract is unclear or contradictory or needs reasonable improvement

## Rules
- Focus on implementing what the technical contract specifies
- Make your code clean and well-structured
- Ensure the deliverable in solution-deliverable/ is ready to use
- Always commit your changes before handing off
`

	case Evaluator:
		return preamble + `# Evaluator Agent

You are a test engineer. Your job is to verify that a solution meets the technical contract.

## Your repository structure
- architecture/ (read-only) - contains the technical contract
- solution-deliverable/ (read-only) - contains the built solution to test
- All other files in this repo are your test code

## Workflow
1. Read files in architecture/ to understand what the solution should do
2. Examine the solution-deliverable/ to understand what was delivered
3. Write comprehensive tests that verify the solution meets the contract
4. Run your tests against the solution deliverable
5. If all tests pass: use the confirm_solution MCP tool
6. If tests fail: use the request_solution_change MCP tool with details about what needs fixing

## Tools
- Use the confirm_solution MCP tool when all tests pass and the solution meets the contract
- Use the request_solution_change MCP tool to send feedback if tests fail, include details of what failed
- Use the request_architecture_change MCP tool if the contract is unclear or contradictory

## Rules
- CRITICAL: When sending feedback via request_solution_change, do NOT reference files from your own repository (your test files, etc.) — the recipient cannot see them. You MAY reference files in architecture/ since those are shared. Describe problems in terms of expected vs actual behavior, error messages, and contract requirements.
- Test based ONLY on the technical contract, not on implementation details
- Write clear, specific test cases
- Provide actionable feedback when tests fail
- Commit your test code to git as you work
`

	case Architect:
		return preamble + `# Architect Agent

You are a software architect. Your job is to create and maintain a technical contract based on the specification.

## Your repository structure
- SPECIFICATION.md - the problem specification (may be provided by user)
- All other files are your technical contract documents

## Workflow
1. Read SPECIFICATION.md to understand the problem
2. Create a clear technical contract that describes:
   - What the solution should implement (interfaces, behavior, features)
   - What deliverable the solution should produce and how to use it
   - What test criteria should be verified against
3. When you make changes to the contract, use the request_solution_change MCP tool to describe what changed and why, providing enough context for the implementer to adjust their existing solution accordingly. You MAY reference files from this repository since they are shared with the implementer.
4. Commit your changes

## Tools
- Use the request_solution_change MCP tool to communicate architecture changes to the implementer with curated descriptions of what changed

## Rules
- Be precise and unambiguous in your technical contract
- Define clear interfaces and expected behaviors
- Specify what the deliverable should be (binary, library, etc.)
- Include enough detail for independent implementation and testing
`

	case Reviewer:
		return preamble + `# Reviewer Agent

You are a code reviewer. Your job is to review solution code for quality and contract compliance.

## Your repository structure
- architecture/ (read-only) - contains the technical contract describing expected behavior
- solution/ (read-only) - contains the solution source code to review

## Workflow
1. Read the technical contract in architecture/ to understand expected behavior
2. Read the code in solution/
3. Review the code for quality, correctness, best practices, and compliance with the technical contract
4. If issues need fixing: use the request_solution_change MCP tool with specific feedback
5. If quality is acceptable: note that the review passed
6. Commit any review notes to git if needed

## Rules
- Focus on code quality and contract compliance — do not rewrite or reimplement the solution
- Provide specific, actionable feedback
- Prioritize correctness and maintainability issues
- When sending feedback via request_solution_change, do NOT reference files from your own repository — the recipient cannot see them. You MAY reference files in architecture/ (shared) or describe issues by referencing the solution's own file paths (which the recipient can see). Describe problems clearly with enough context for the recipient to act independently.
`
	}
	return ""
}

// UpdateClaudeMDFiles checks each agent's CLAUDE.md for a <this_agent_description> block
// and replaces it with the current auto-generated content. Returns the list of agent types
// whose files were updated. If a file exists but has no block, it is skipped (user opted out).
// If a file doesn't exist, it is not created.
func UpdateClaudeMDFiles(baseDir string) ([]AgentType, error) {
	var updated []AgentType
	for _, at := range AllTypes() {
		repoDir := filepath.Join(baseDir, RepoDir(at))
		claudePath := filepath.Join(repoDir, ".claude", "CLAUDE.md")

		content, err := os.ReadFile(claudePath)
		if err != nil {
			if os.IsNotExist(err) {
				continue // File doesn't exist — don't create it
			}
			return updated, fmt.Errorf("read %s CLAUDE.md: %w", at, err)
		}

		fileStr := string(content)

		// Check if the file contains a <this_agent_description> block
		openTag := "<this_agent_description>"
		closeTag := "</this_agent_description>"
		openIdx := strings.Index(fileStr, openTag)
		closeIdx := strings.Index(fileStr, closeTag)
		if openIdx < 0 || closeIdx < 0 || closeIdx < openIdx {
			continue // No block found — user opted out, skip
		}

		// Find the start of the auto-generated comment preceding the block.
		// We replace from the comment through the closing tag.
		commentStart := strings.LastIndex(fileStr[:openIdx], AutoManagedBlockComment)
		if commentStart < 0 {
			// Comment not found, replace from the opening tag
			commentStart = openIdx
		}

		blockEnd := closeIdx + len(closeTag)
		// Include trailing newline if present
		if blockEnd < len(fileStr) && fileStr[blockEnd] == '\n' {
			blockEnd++
		}

		// Build the new block
		newBlock := AutoManagedBlockComment + "\n" + openTag + "\n" + agentInstructions(at) + closeTag + "\n"

		newContent := fileStr[:commentStart] + newBlock + fileStr[blockEnd:]

		if newContent == fileStr {
			continue // No changes needed
		}

		if err := os.WriteFile(claudePath, []byte(newContent), 0644); err != nil {
			return updated, fmt.Errorf("write %s CLAUDE.md: %w", at, err)
		}
		updated = append(updated, at)
	}
	return updated, nil
}

// AllowedTools returns the comma-separated tool pattern string for --allowedTools.
func AllowedTools() string {
	return "Bash(*),Read(/*),Write(/*),Edit(/*),Glob(/*),Grep(/*),WebFetch(*),WebSearch(*),mcp__bobbi__*"
}

func McpJSON(agentType AgentType, bobbiBin string, queuesDir string) string {
	// Normalize to forward slashes so the command path is valid JSON on Windows
	bobbiBin = strings.ReplaceAll(bobbiBin, `\`, "/")
	queuesDir = strings.ReplaceAll(queuesDir, `\`, "/")

	// Use json.Marshal for string values to ensure valid JSON escaping
	// (Go's %q can produce escape sequences like \a or \v that are not valid in JSON)
	cmdJSON, _ := json.Marshal(bobbiBin)
	agentJSON, _ := json.Marshal(string(agentType))
	queuesJSON, _ := json.Marshal(queuesDir)

	return fmt.Sprintf(`{
  "mcpServers": {
    "bobbi": {
      "type": "stdio",
      "command": %s,
      "args": ["mcp", "--agent", %s, "--queues-dir", %s]
    }
  }
}`, string(cmdJSON), string(agentJSON), string(queuesJSON))
}

func GitIgnore(agentType AgentType) string {
	switch agentType {
	case Solver:
		return `architecture/
solution-deliverable/
`
	case Evaluator:
		return `architecture/
solution-deliverable/
`
	case Architect:
		return ""
	case Reviewer:
		return `architecture/
evaluation/
solution/
`
	}
	return ""
}
